# Site settings
env: prod
port: 4000
assets_version: 0.0.0

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
name: I2Soft Technologies
description: I2Soft Technologies

# Post settings
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Sass settings
sass:
    style: :compressed